pipeline {
    agent any
    environment {
        REPO = "s10-blockchain-contract-sub2/S10P22C207"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(
                        branches: [[name: 'develop']],
                        extensions: [submodule(parentCredentials: true, trackingSubmodules: true)],
                        utilsRemoteConfigs: [[credentialsId: 'github-access-token', url: 'https://github.com/boongbangsaurus/boongbang-settings']]
                )
            }
        }
        stage('Move .env File') {
            steps {
                script{
                    sh 'cp ../environments/gradle.properties backend/user/gradle.properties'
                }
            }
        }
        stage('Setup Environment') {
            steps {
                script{
                    sh "chmod +x ./backend/utils/gradlew"
                }
            }
        }
        stage("Build & Run") {
            steps {
                dir("infra/jenkins/back/utils"){
                    script {
                        try {
                            sh "docker build -t kimdahui/utils ."
                            sh "docker run -d --name utils"
                        }catch (Exception e) {
                            sh "docker restart utils"
                        }
                    }
                }
            }
        }
        stage('Prune old images'){
            steps{
                script{
                    sh "yes | docker system prune --filter until=1h"
                }
            }
        }
    }
    post {
        always {
            script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                mattermostSend (color: currentBuild.currentResult=='SUCCESS'?'good':'danger',
                        message: "빌드 ${currentBuild.currentResult}: ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)",
                        endpoint: 'https://meeting.ssafy.com/hooks/8656byf6wbn3mdns9ym35suhze',
                        channel: 'Jenkins'
                )
            }
        }
    }
}
