pipeline {
    agent any
    environment {
        REPO = "s10-blockchain-contract-sub2/S10P22C207"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(
                        branches: [[name: 'release-test']],
                        extensions: [submodule(parentCredentials: true, trackingSubmodules: true)],
                        userRemoteConfigs: [
                                [credentialsId: 'github-access-token', url: 'https://github.com/boongbangsaurus/boongbang-settings']]
                )
            }
        }
        stage('Move .env File') {
            steps {
                script{
                    sh 'cp ../environments/.env backend/eureka/.env'
                    sh 'cp ../environments/gradle.properties backend/eureka/gradle.properties'
                    sh "mkdir -p backend/eureka/src/main/resources"
                    sh "ls -al secure-settings/back/eureka"
                    // find 명령어를 사용하여 .yml 파일을  찾고, 각 파일에 대해 cp 명령어를 실행
                    sh "cp secure-settings/back/eureka/eureka-service-default.yml backend/eureka/src/main/resources/application.yml"
                }
            }
        }
        stage('Setup Environment') {
            steps {
                script{
                    sh "chmod +x ./backend/eureka/gradlew"
                }
            }
        }
        stage("Build & Run") {
            steps {
                dir("backend/eureka"){
                    script {
                        try {
                            sh "docker-compose -p eureka-project build --no-cache"
                            sh "docker-compose -p eureka-project up -d"
                        }catch (Exception e) {
                            sh "docker stop eureka"
                            sh "docker-compose -p eureka-project build --no-cache"
                            sh "docker-compose -p eureka-project up -d"
                        }
                    }
                }
            }
        }
        stage('Prune old images'){
            steps{
                script{
                    sh "yes | docker system prune --filter until=1h"
                }
            }
        }
    }
    post {
        always {
            script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                mattermostSend (color: currentBuild.currentResult=='SUCCESS'?'good':'danger',
                        message: "빌드 ${currentBuild.currentResult}: ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)",
                        endpoint: 'https://meeting.ssafy.com/hooks/8656byf6wbn3mdns9ym35suhze',
                        channel: 'Jenkins'
                )
            }
        }
    }
}
