version: '3.3'

services:
  eureka:
    container_name: eureka
    image: kimdahui/eureka
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8761:8761"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://${CONFIG_USERNAME}:${CONFIG_PASSWORD}@config:9000
    networks:
      - jenkins-project_socon-net
    env_file:
      - ../../.env

networks:
  jenkins-project_socon-net:
    external: true

