version: '3.3'

services:
  eureka:
    container_name: eureka
    image: kimdahui/eureka
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8761:8761"
    environment:
      - CONFIG_USERNAME=${CONFIG_USERNAME}
      - CONFIG_PASSWORD=${CONFIG_PASSWORD}
    networks:
      - jenkins-project_socon-net

networks:
  jenkins-project_socon-net:
    external: true
