name: socon
description: "지역 상생을 위한 소상공인 기프티콘 발행 및 커뮤니티 플랫폼"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  flutter_feather_icons: ^2.0.0
  fluentui_emoji_icon: ^0.0.2
  go_router: ^13.2.1
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.20
  provider: ^6.0.0
  pretty_qr_code: ^3.3.0
  image_gallery_saver: ^2.0.3
  webview_flutter: ^4.7.0
  animated_text_kit: ^4.2.2
  shared_preferences: ^2.2.2
  confetti: ^0.7.0
  intl: ^0.19.0
  google_maps_flutter: ^2.6.0
  location: ^5.0.3
  flutter_local_notifications: ^17.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true


  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/pretendard/Pretendard-Black.otf
          weight: 900
    - family: BagelFatOne
      fonts:
        - asset: assets/fonts/bagelFatOne/BagelFatOne-Regular.ttf

  assets:
    - assets/icons/
    - assets/images/
