version: '3.3'

services:
  config:
    container_name: config
    image: kimdahui/config
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - CONFIG_PRIVATE_KEY=${CONFIG_PRIVATE_KEY}
      - CONFIG_USERNAME=${CONFIG_USERNAME}
      - CONFIG_PASSWORD=${CONFIG_PASSWORD}
    networks:
      - jenkins-project_socon-net
    env_file:
      - ../../.env
    command: env

networks:
  jenkins-project_socon-net:
    external: true

