version: '3.3'

services:
  notification:
    container_name: notification
    image: kimdahui/notification
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8010:8010"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://${CONFIG_USERNAME}:${CONFIG_PASSWORD}@config:9000
    networks:
      - jenkins-project_socon-net
    env_file:
      - ../../.env

networks:
  jenkins-project_socon-net:
    external: true

