server:
  port: 8000

eureka:
  instance:
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    disable-delta: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        # auth-service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - AuthFilter
        # user-service Auth filtering
#        - id: user-service
#          uri: lb://MAIN-SERVICE
#          predicates:
#            - Path=/main-service/applyments/**, /main-service/likes/**, /main-service/notifications/**, /main-service/posts
#            - Method=PATCH,DELETE,POST
#          filters:
#            - AuthPermissionFilter

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /actuator  # ?? ??
      exposure:
        include: info, health
    jmx:
      exposure:
        exclude: ['*']
