version: '3.3'

services:
  gateway:
    container_name: gateway
    image: kimdahui/gateway
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - CONFIG_USERNAME=${CONFIG_USERNAME}
      - CONFIG_PASSWORD=${CONFIG_PASSWORD}
    networks:
      - jenkins-project_socon-net

networks:
  jenkins-project_socon-net:
    external: true
