version: '3.3'

services:
  payment:
    container_name: payment
    image: kimdahui/payment
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8020:8020"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://${CONFIG_USERNAME}:${CONFIG_PASSWORD}@config:9000
    networks:
      - jenkins-project_socon-net
    env_file:
      - ../../.env

networks:
  jenkins-project_socon-net:
    external: true

