spring:
  application:
    name: eureka-service
  config:
    import: optional:configserver:http://${CONFIG_USERNAME}:${CONFIG_PASSWORD}@config:9000
  profiles:
    active: prod
  cache:
    type: redis

logging:
  level:
    org.springframework.cloud.config.client: DEBUG

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: ['refresh']
