version: '3.3'

services:
  socon:
    container_name: socon
    image: kimdahui/socon
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8030:8030"
    environment:
      - CONFIG_USERNAME=${CONFIG_USERNAME}
      - CONFIG_PASSWORD=${CONFIG_PASSWORD}
    networks:
      - jenkins-project_socon-net

networks:
  jenkins-project_socon-net:
    external: true
