pipeline {
    agent any
    environment {
        REPO = "s10-blockchain-contract-sub2/S10P22C207"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(
                        branches: [[name: 'develop']],
                        extensions: [submodule(parentCredentials: true, trackingSubmodules: true)],
                        userRemoteConfigs: [[credentialsId: 'github-access-token', url: 'https://github.com/boongbangsaurus/boongbang-settings']]
                )
            }
        }
        stage('Move .env File') {
            steps {
                script{
                    sh 'cp secure-settings/back/.env .env'
                    sh "cp secure-settings/back/gateway/gradle.properties backend/gateway/gradle.properties"
                    sh "mkdir -p backend/gateway/src/resources"
                    // find 명령어를 사용하여 .yml 파일을 찾고, 각 파일에 대해 cp 명령어를 실행
                    sh "find secure-settings/back/gateway -name '*.yml' -exec cp {} backend/gateway/src/resources \\;"
                    // 동일한 디렉토리 내 모든 .yml 파일을 복사
                    sh "find secure-settings/back -maxdepth 1 -name '*.yml' -exec cp {} backend/gateway/src/resources \\;"
                }
            }
        }
        stage('Setup Environment') {
            steps {
                script{
                    sh "chmod +x ./backend/gateway/gradlew"
                }
            }
        }
        stage("Build & Run") {
            steps {
                dir("backend/gateway"){
                    script {
                        try {
                            sh "docker build -t kimdahui/gateway ."
                            sh '''
                            docker run -d --name gateway \\
                            --network jenkins-project_socon-net \\
                            --restart unless-stopped \\
                            -e "SPRING_PROFILES_ACTIVE=prod,gateway_prod" \\
                            -e "SERVER_PORT=8000" \\
                            -p 8000:8000 kimdahui/gateway
                            '''
                        }catch (Exception e) {
                            sh "docker restart gateway"
                        }
                    }
                }
            }
        }
        stage('Prune old images'){
            steps{
                script{
                    sh "yes | docker system prune --filter until=1h"
                }
            }
        }
    }
    post {
        always {
            script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                mattermostSend (color: currentBuild.currentResult=='SUCCESS'?'good':'danger',
                        message: "빌드 ${currentBuild.currentResult}: ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)",
                        endpoint: 'https://meeting.ssafy.com/hooks/8656byf6wbn3mdns9ym35suhze',
                        channel: 'Jenkins'
                )
            }
        }
    }
}
