spring:
  config:
    activate:
      on-profile: credential

fcm:
  project-id: socon-socon
  config: |
    {
      "type": "service_account",
      "project_id": "socon-socon",
      "private_key_id": "f5b716bed25d5dc751d04629a899ac7ed0ee24f5",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCq/3s6kj5xyQ2C\n7yEXfXNIGLIvcN3GJUZWvlIcmReqEfVZ47Vf77EEqG9ne7qMmD+xGosedNA4MMuI\nl9q1h4sW8MG/uGhuVY7WX9FdaPXRx7IPIqJRoczQJp0w12pElFbTj/1dDa2VgEKA\nrftP6Gnis4XFYA4KtWv2RD2yfJ8/8HdAh/o9IIeOnJQaLhJuoWMoLuQbKndipWJP\naBYL5d0Sa5rvUjEt1dO9gm8Sg+QLrrPvvBQQm3W2W33PDlxSPemVBxILjPDHQP7M\nwwZDBdOphjbRkihlvu925HyUXsNeNTIWXr4EmsVQxOuAapg+6YLh/Nvsw9ge0jzK\nS16FrmaNAgMBAAECggEAGKH0fbe+9JO2lU++x9w7vN1H39Mls2s/snO4ruNz1/09\nx4zonhEQgkAESlc1xJaTCD9vXnwL2ahXzY24hRFpPS0B8A0PyCMdkC6d4ZOi460d\nbpY55UIGV87UMoq5hXcL+e6CXEMB6Ckhi1lkvDpZ9H0RbmEbrLm9O2zRqXJP230b\nTY0sVhrzz2+yMXCrQVJGzrjDFU6UFX4ms7tyMdUNQzjUozYMvY5C15WoSwQONOfw\nemCr2yf14dsaI+d7gxOdjd7uGytHMHf1MpXGZeybT2lNdP6bjCYcFElHrkMIhyMl\nVnxV8QUofsjtmyI7Bk7lBtITHfUEg+WQ3WWcNsb5WQKBgQDaztijmxfBYYy2M4Hw\nU70cZcYJRINL2+L36I4EdynlSvWTOnBuLOzSL0nTv9RWqFaVPrBQFusTs6Mhw8xM\nFM2bIllTBlWsW4sxgyrw3/CYWDhK1XlS9plPnVlUG1Kj2HHf75Qoaio5B0BYVdsh\nabPGQCnY+UpI2B0vrEQY5YrNCQKBgQDIED4RsEF9lNfojdzj4TbNTESXgaGzxXJG\nO0WIhtZPGbIxHMDX9/D85UyIrPsiK6ZXLiFZxz5lzGEO4Iai88DB7IUxr8EvgdqD\nXCfzVj4+7i1Pn34QsnPeoJUanXxyAZlpvUNIJ9zs559lYpnfZJqmCA61zcXB/IHt\n996RLpHyZQKBgGm5HDAhFh9YNRcsWBJ5Q5zfCAseUZpryoUilsxNj668w1+6Eu0J\nQ/xi4PcxbzXX7M38FlD8YeWJHL+JzcLNInNc63AUVX0MVns795mfeq8BoWF3OEH/\n6R/w1WKwOQP15z/ekOXeNjyL5mlIQrMoUbbu9cli2qPL2H5abCTjdGeRAoGAUNKf\nAK5gBsfW4dBN6JHXfeDN5RctqF6f59eSI7G1aodLAaRIE/fKl6Ba5uxbGFbiAF5W\ngtqHTsDehRAX1ET9HlrbBFOoi/S9vkvAqAGza+D01THtz/kH7myZUANHfxc+TwVy\n5PeVvO9l6aOH3kPaZjDjIHdc6R2FsAlvFN/nfjECgYBSBom7JIINqtmpgAR5QbE7\n6WeM75rPHUiuxwDHGlsLvnpr39clsXv133vfkWNVgkvGJJGXQljp33kFlvE/jJ94\n7J6aQ7lE5CCHJ9gKHZ8FmBr5WLYjlxL7p8Rkm5EXYaVlVuuJ06bXIfNLBDF2tuLH\nW3dDUGEwEonFT6WZZKIrYw==\n-----END PRIVATE KEY-----\n",
      "client_email": "firebase-adminsdk-n18al@socon-socon.iam.gserviceaccount.com",
      "client_id": "107744887339641930439",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-n18al%40socon-socon.iam.gserviceaccount.com",
      "universe_domain": "googleapis.com"
    }
